source only configuration files ending with .conf

diff --git a/usr/bin/vpn-firewall b/usr/bin/vpn-firewall
--- a/usr/bin/vpn-firewall
+++ b/usr/bin/vpn-firewall
@@ -25,20 +25,18 @@ trap "error_handler" ERR INT TERM
 ## source config folder
 ###########################
 
-for i in /etc/vpn-firewall.d/*; do
-   if [ -f "$i" ]; then
-      ## If the last character is a ~, ignore that file, because it was created
-      ## by some editor, which creates backup files.
-      if [ "${i: -1}" = "~" ]; then
-         continue
-      fi
-      ## Skipping files such as .dpkg-old and .dpkg-dist.
-      if ( echo "$i" | grep -q ".dpkg-" ); then
-         true "skip $i"
-         continue
-      fi
-      source "$i"
+shopt -s nullglob
+for i in /etc/vpn-firewall.d/*.conf; do
+   bash_n_exit_code="0"
+   bash_n_output="$(bash -n "$i" 2>&1)" || { bash_n_exit_code="$?" ; true; };
+   if [ ! "$bash_n_exit_code" = "0" ]; then
+      echo "Invalid config file: $i
+bash_n_exit_code: $bash_n_exit_code
+bash_n_output:
+$bash_n_output" >&2
+      exit 1
    fi
+   source "$i"
 done
 
 #############
